---
title: "OXR Kegg query pathways"
output: html_document
date: "2023-11-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The purpose of this script is to take the tables, specifically the pathway-to-ko.txt in the kegg_query_all_transcripts directory, make it into long format, add in the pathway names and class then, incorporate into the count data.

Reference the kegg_querying.txt file for what was done to get here.

OXR-9
```{r}
library(dplyr)


# Read in the 
path.to.ko <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-9/trycycler/eggNOG_annotations/kegg_query_all_transcripts/Finaloutput.txt", header=F, sep = "")

names(path.to.ko) <- c("pathway","ko")

# read in pathway_name.txt
path.name <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-9/trycycler/eggNOG_annotations/kegg_query_all_transcripts/pathway_name.txt", header=F, sep = "\t")

names(path.name) <- c("pathway","name")

# read in pathway_name.txt
path.class <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-9/trycycler/eggNOG_annotations/kegg_query_all_transcripts/pathway-to-class.txt", header=F, sep = "\t")

names(path.class) <- c("pathway","class","description")
# something was funky, so I fixed it
path.class[path.class == "Folding"] <- "Folding sorting and degradation"
path.class <- path.class[- grep("sorting and degradation", path.class$pathway),]

# Merge the pathway information with the KO's
pathway.all <- merge(path.to.ko, path.name, by = "pathway", all = T)
pathway.all <- merge(pathway.all, path.class, by = "pathway", all = T)

# read in the KO's for the organism
trans.ko <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-9/trycycler/eggNOG_annotations/OXR-9_ko.txt", header = T, sep = "\t")

names(trans.ko)[names(trans.ko) == "value"] <- "ko"

# Merge the pathway information with the ko list
all <- merge(trans.ko, pathway.all, by = "ko", all = T)
all <- all[-c(4:12)]

# read in the annos with the DESeq info
deseq <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-9/trycycler/eggNOG_annotations/OXR-9_annos_w-DESeq.txt", header = T, sep = "\t")

deseq <- deseq[,c(1:8,33,34,46)]

# merge with all the pathway information
WOW <- merge(deseq, all, by = "eggNOG_name", all = T)
# remove NA's in the eggNOG_name field
WOW <- WOW[! is.na(WOW$eggNOG_name),]

output.file <- file("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-9/trycycler/eggNOG_annotations/OXR-9_all_data.txt", "wb")
write.table(WOW, file = output.file, row.names = F, col.names = T, sep = "\t")
close(output.file)

```

OXR-11
```{r}
library(dplyr)


# Read in the 
path.to.ko <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-11/trycycler/eggNOG_annotations/kegg_query_all_transcripts/Finaloutput.txt", header=F, sep = "")

names(path.to.ko) <- c("pathway","ko")

# read in pathway_name.txt
path.name <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-11/trycycler/eggNOG_annotations/kegg_query_all_transcripts/pathway_name.txt", header=F, sep = "\t")

names(path.name) <- c("pathway","name")

# read in pathway_name.txt
path.class <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-11/trycycler/eggNOG_annotations/kegg_query_all_transcripts/pathway-to-class.txt", header=F, sep = "\t")

names(path.class) <- c("pathway","class","description")
# something was funky, so I fixed it
path.class[path.class == "Folding"] <- "Folding sorting and degradation"
path.class <- path.class[- grep("sorting and degradation", path.class$pathway),]

# Merge the pathway information with the KO's
pathway.all <- merge(path.to.ko, path.name, by = "pathway", all = T)
pathway.all <- merge(pathway.all, path.class, by = "pathway", all = T)

# read in the KO's for the organism
trans.ko <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-11/trycycler/eggNOG_annotations/OXR-11_ko.txt", header = T, sep = "\t")

names(trans.ko)[names(trans.ko) == "value"] <- "ko"

# Merge the pathway information with the ko list
all <- merge(trans.ko, pathway.all, by = "ko", all = T)
all <- all[-c(4:12)]

# read in the annos with the DESeq info
deseq <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-11/trycycler/eggNOG_annotations/OXR-11_annos_w-DESeq.txt", header = T, sep = "\t")

deseq <- deseq[,c(1:8,33,34,46)]

# merge with all the pathway information
WOW <- merge(deseq, all, by = "eggNOG_name", all = T)
# remove NA's in the eggNOG_name field
WOW <- WOW[! is.na(WOW$eggNOG_name),]

output.file <- file("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-11/trycycler/eggNOG_annotations/OXR-11_all_data.txt", "wb")
write.table(WOW, file = output.file, row.names = F, col.names = T, sep = "\t")
close(output.file)

```

OXR-76
```{r}
library(dplyr)


# Read in the 
path.to.ko <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-76/trycycler/eggNOG_annotations/kegg_query_all_transcripts/Finaloutput.txt", header=F, sep = "")

names(path.to.ko) <- c("pathway","ko")

# read in pathway_name.txt
path.name <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-76/trycycler/eggNOG_annotations/kegg_query_all_transcripts/pathway_name.txt", header=F, sep = "\t")

names(path.name) <- c("pathway","name")

# read in pathway_name.txt
path.class <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-76/trycycler/eggNOG_annotations/kegg_query_all_transcripts/pathway-to-class.txt", header=F, sep = "\t")

names(path.class) <- c("pathway","class","description")
# something was funky, so I fixed it
path.class[path.class == "Folding"] <- "Folding sorting and degradation"
path.class <- path.class[- grep("sorting and degradation", path.class$pathway),]

# Merge the pathway information with the KO's
pathway.all <- merge(path.to.ko, path.name, by = "pathway", all = T)
pathway.all <- merge(pathway.all, path.class, by = "pathway", all = T)

# read in the KO's for the organism
trans.ko <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-76/trycycler/eggNOG_annotations/OXR-76_ko.txt", header = T, sep = "\t")

names(trans.ko)[names(trans.ko) == "value"] <- "ko"

# Merge the pathway information with the ko list
all <- merge(trans.ko, pathway.all, by = "ko", all = T)
all <- all[-c(4:12)]

# read in the annos with the DESeq info
deseq <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-76/trycycler/eggNOG_annotations/OXR-76_annos_w-DESeq.txt", header = T, sep = "\t")

deseq <- deseq[,c(1:8,33,34,46)]

# merge with all the pathway information
WOW <- merge(deseq, all, by = "eggNOG_name", all = T)
# remove NA's in the eggNOG_name field
WOW <- WOW[! is.na(WOW$eggNOG_name),]

output.file <- file("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-76/trycycler/eggNOG_annotations/OXR-76_all_data.txt", "wb")
write.table(WOW, file = output.file, row.names = F, col.names = T, sep = "\t")
close(output.file)

```

OXR-85
```{r}
library(dplyr)


# Read in the 
path.to.ko <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-85/trycycler/eggNOG_annotations/kegg_query_all_transcripts/Finaloutput.txt", header=F, sep = "")

names(path.to.ko) <- c("pathway","ko")

# read in pathway_name.txt
path.name <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-85/trycycler/eggNOG_annotations/kegg_query_all_transcripts/pathway_name.txt", header=F, sep = "\t")

names(path.name) <- c("pathway","name")

# read in pathway_name.txt
path.class <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-85/trycycler/eggNOG_annotations/kegg_query_all_transcripts/pathway-to-class.txt", header=F, sep = "\t")

names(path.class) <- c("pathway","class","description")
# something was funky, so I fixed it
path.class[path.class == "Folding"] <- "Folding sorting and degradation"
path.class <- path.class[- grep("sorting and degradation", path.class$pathway),]

# Merge the pathway information with the KO's
pathway.all <- merge(path.to.ko, path.name, by = "pathway", all = T)
pathway.all <- merge(pathway.all, path.class, by = "pathway", all = T)

# read in the KO's for the organism
trans.ko <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-85/trycycler/eggNOG_annotations/OXR-85_ko.txt", header = T, sep = "\t")

names(trans.ko)[names(trans.ko) == "value"] <- "ko"

# Merge the pathway information with the ko list
all <- merge(trans.ko, pathway.all, by = "ko", all = T)
all <- all[-c(4:12)]

# read in the annos with the DESeq info
deseq <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-85/trycycler/eggNOG_annotations/OXR-85_annos_w-DESeq.txt", header = T, sep = "\t")

deseq <- deseq[,c(1:8,33,34,46)]

# merge with all the pathway information
WOW <- merge(deseq, all, by = "eggNOG_name", all = T)
# remove NA's in the eggNOG_name field
WOW <- WOW[! is.na(WOW$eggNOG_name),]

output.file <- file("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-85/trycycler/eggNOG_annotations/OXR-85_all_data.txt", "wb")
write.table(WOW, file = output.file, row.names = F, col.names = T, sep = "\t")
close(output.file)

```

OXR-96
```{r}
library(dplyr)


# Read in the 
path.to.ko <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-96/trycycler/eggNOG_annotations/kegg_query_all_transcripts/Finaloutput.txt", header=F, sep = "")

names(path.to.ko) <- c("pathway","ko")

# read in pathway_name.txt
path.name <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-96/trycycler/eggNOG_annotations/kegg_query_all_transcripts/pathway_name.txt", header=F, sep = "\t")

names(path.name) <- c("pathway","name")

# read in pathway_name.txt
path.class <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-96/trycycler/eggNOG_annotations/kegg_query_all_transcripts/pathway-to-class.txt", header=F, sep = "\t")

names(path.class) <- c("pathway","class","description")
# something was funky, so I fixed it
path.class[path.class == "Folding"] <- "Folding sorting and degradation"
path.class <- path.class[- grep("sorting and degradation", path.class$pathway),]

# Merge the pathway information with the KO's
pathway.all <- merge(path.to.ko, path.name, by = "pathway", all = T)
pathway.all <- merge(pathway.all, path.class, by = "pathway", all = T)

# read in the KO's for the organism
trans.ko <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-96/trycycler/eggNOG_annotations/OXR-96_ko.txt", header = T, sep = "\t")

names(trans.ko)[names(trans.ko) == "value"] <- "ko"

# Merge the pathway information with the ko list
all <- merge(trans.ko, pathway.all, by = "ko", all = T)
all <- all[-c(4:12)]

# read in the annos with the DESeq info
deseq <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-96/trycycler/eggNOG_annotations/OXR-96_annos_w-DESeq.txt", header = T, sep = "\t")

deseq <- deseq[,c(1:8,33,34,46)]

# merge with all the pathway information
WOW <- merge(deseq, all, by = "eggNOG_name", all = T)
# remove NA's in the eggNOG_name field
WOW <- WOW[! is.na(WOW$eggNOG_name),]

output.file <- file("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-96/trycycler/eggNOG_annotations/OXR-96_all_data.txt", "wb")
write.table(WOW, file = output.file, row.names = F, col.names = T, sep = "\t")
close(output.file)

```

OXR-134
```{r}
library(dplyr)


# Read in the 
path.to.ko <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-134/trycycler/eggNOG_annotations/kegg_query_all_transcripts/Finaloutput.txt", header=F, sep = "")

names(path.to.ko) <- c("pathway","ko")

# read in pathway_name.txt
path.name <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-134/trycycler/eggNOG_annotations/kegg_query_all_transcripts/pathway_name.txt", header=F, sep = "\t")

names(path.name) <- c("pathway","name")

# read in pathway_name.txt
path.class <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-134/trycycler/eggNOG_annotations/kegg_query_all_transcripts/pathway-to-class.txt", header=F, sep = "\t")

names(path.class) <- c("pathway","class","description")
# something was funky, so I fixed it
path.class[path.class == "Folding"] <- "Folding sorting and degradation"
path.class <- path.class[- grep("sorting and degradation", path.class$pathway),]

# Merge the pathway information with the KO's
pathway.all <- merge(path.to.ko, path.name, by = "pathway", all = T)
pathway.all <- merge(pathway.all, path.class, by = "pathway", all = T)

# read in the KO's for the organism
trans.ko <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-134/trycycler/eggNOG_annotations/OXR-134_ko.txt", header = T, sep = "\t")

names(trans.ko)[names(trans.ko) == "value"] <- "ko"

# Merge the pathway information with the ko list
all <- merge(trans.ko, pathway.all, by = "ko", all = T)
all <- all[-c(4:12)]

# read in the annos with the DESeq info
deseq <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-134/trycycler/eggNOG_annotations/OXR-134_annos_w-DESeq.txt", header = T, sep = "\t")

deseq <- deseq[,c(1:8,33,34,46)]

# merge with all the pathway information
WOW <- merge(deseq, all, by = "eggNOG_name", all = T)
# remove NA's in the eggNOG_name field
WOW <- WOW[! is.na(WOW$eggNOG_name),]

output.file <- file("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-134/trycycler/eggNOG_annotations/OXR-134_all_data.txt", "wb")
write.table(WOW, file = output.file, row.names = F, col.names = T, sep = "\t")
close(output.file)

```

OXR-137
```{r}
library(dplyr)


# Read in the 
path.to.ko <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-137/trycycler/eggNOG_annotations/kegg_query_all_transcripts/Finaloutput.txt", header=F, sep = "")

names(path.to.ko) <- c("pathway","ko")

# read in pathway_name.txt
path.name <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-137/trycycler/eggNOG_annotations/kegg_query_all_transcripts/pathway_name.txt", header=F, sep = "\t")

names(path.name) <- c("pathway","name")

# read in pathway_name.txt
path.class <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-137/trycycler/eggNOG_annotations/kegg_query_all_transcripts/pathway-to-class.txt", header=F, sep = "\t")

names(path.class) <- c("pathway","class","description")
# something was funky, so I fixed it
path.class[path.class == "Folding"] <- "Folding sorting and degradation"
path.class <- path.class[- grep("sorting and degradation", path.class$pathway),]

# Merge the pathway information with the KO's
pathway.all <- merge(path.to.ko, path.name, by = "pathway", all = T)
pathway.all <- merge(pathway.all, path.class, by = "pathway", all = T)

# read in the KO's for the organism
trans.ko <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-137/trycycler/eggNOG_annotations/OXR-137_ko.txt", header = T, sep = "\t")

names(trans.ko)[names(trans.ko) == "value"] <- "ko"

# Merge the pathway information with the ko list
all <- merge(trans.ko, pathway.all, by = "ko", all = T)
all <- all[-c(4:12)]

# read in the annos with the DESeq info
deseq <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-137/trycycler/eggNOG_annotations/OXR-137_annos_w-DESeq.txt", header = T, sep = "\t")

deseq <- deseq[,c(1:8,33,34,46)]

# merge with all the pathway information
WOW <- merge(deseq, all, by = "eggNOG_name", all = T)
# remove NA's in the eggNOG_name field
WOW <- WOW[! is.na(WOW$eggNOG_name),]

output.file <- file("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-137/trycycler/eggNOG_annotations/OXR-137_all_data.txt", "wb")
write.table(WOW, file = output.file, row.names = F, col.names = T, sep = "\t")
close(output.file)

```

OXR-159
```{r}
library(dplyr)


# Read in the 
path.to.ko <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-159/trycycler/eggNOG_annotations/kegg_query_all_transcripts/Finaloutput.txt", header=F, sep = "")

names(path.to.ko) <- c("pathway","ko")

# read in pathway_name.txt
path.name <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-159/trycycler/eggNOG_annotations/kegg_query_all_transcripts/pathway_name.txt", header=F, sep = "\t")

names(path.name) <- c("pathway","name")

# read in pathway_name.txt
path.class <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-159/trycycler/eggNOG_annotations/kegg_query_all_transcripts/pathway-to-class.txt", header=F, sep = "\t")

names(path.class) <- c("pathway","class","description")
# something was funky, so I fixed it
path.class[path.class == "Folding"] <- "Folding sorting and degradation"
path.class <- path.class[- grep("sorting and degradation", path.class$pathway),]

# Merge the pathway information with the KO's
pathway.all <- merge(path.to.ko, path.name, by = "pathway", all = T)
pathway.all <- merge(pathway.all, path.class, by = "pathway", all = T)

# read in the KO's for the organism
trans.ko <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-159/trycycler/eggNOG_annotations/OXR-159_ko.txt", header = T, sep = "\t")

names(trans.ko)[names(trans.ko) == "value"] <- "ko"

# Merge the pathway information with the ko list
all <- merge(trans.ko, pathway.all, by = "ko", all = T)
all <- all[-c(4:12)]

# read in the annos with the DESeq info
deseq <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-159/trycycler/eggNOG_annotations/OXR-159_annos_w-DESeq.txt", header = T, sep = "\t")

deseq <- deseq[,c(1:8,33,34,46)]

# merge with all the pathway information
WOW <- merge(deseq, all, by = "eggNOG_name", all = T)
# remove NA's in the eggNOG_name field
WOW <- WOW[! is.na(WOW$eggNOG_name),]

output.file <- file("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-159/trycycler/eggNOG_annotations/OXR-159_all_data.txt", "wb")
write.table(WOW, file = output.file, row.names = F, col.names = T, sep = "\t")
close(output.file)

```

OXR-189
```{r}
library(dplyr)


# Read in the 
path.to.ko <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-189/trycycler/eggNOG_annotations/kegg_query_all_transcripts/Finaloutput.txt", header=F, sep = "")

names(path.to.ko) <- c("pathway","ko")

# read in pathway_name.txt
path.name <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-189/trycycler/eggNOG_annotations/kegg_query_all_transcripts/pathway_name.txt", header=F, sep = "\t")

names(path.name) <- c("pathway","name")

# read in pathway_name.txt
path.class <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-189/trycycler/eggNOG_annotations/kegg_query_all_transcripts/pathway-to-class.txt", header=F, sep = "\t")

names(path.class) <- c("pathway","class","description")
# something was funky, so I fixed it
path.class[path.class == "Folding"] <- "Folding sorting and degradation"
path.class <- path.class[- grep("sorting and degradation", path.class$pathway),]

# Merge the pathway information with the KO's
pathway.all <- merge(path.to.ko, path.name, by = "pathway", all = T)
pathway.all <- merge(pathway.all, path.class, by = "pathway", all = T)

# read in the KO's for the organism
trans.ko <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-189/trycycler/eggNOG_annotations/OXR-189_ko.txt", header = T, sep = "\t")

names(trans.ko)[names(trans.ko) == "value"] <- "ko"

# Merge the pathway information with the ko list
all <- merge(trans.ko, pathway.all, by = "ko", all = T)
all <- all[-c(4:12)]

# read in the annos with the DESeq info
deseq <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-189/trycycler/eggNOG_annotations/OXR-189_annos_w-DESeq.txt", header = T, sep = "\t")

deseq <- deseq[,c(1:8,33,34,46)]

# merge with all the pathway information
WOW <- merge(deseq, all, by = "eggNOG_name", all = T)
# remove NA's in the eggNOG_name field
WOW <- WOW[! is.na(WOW$eggNOG_name),]

output.file <- file("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-189/trycycler/eggNOG_annotations/OXR-189_all_data.txt", "wb")
write.table(WOW, file = output.file, row.names = F, col.names = T, sep = "\t")
close(output.file)

```

OXR-199
```{r}
library(dplyr)


# Read in the 
path.to.ko <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-199/trycycler/eggNOG_annotations/kegg_query_all_transcripts/Finaloutput.txt", header=F, sep = "")

names(path.to.ko) <- c("pathway","ko")

# read in pathway_name.txt
path.name <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-199/trycycler/eggNOG_annotations/kegg_query_all_transcripts/pathway_name.txt", header=F, sep = "\t")

names(path.name) <- c("pathway","name")

# read in pathway_name.txt
path.class <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-199/trycycler/eggNOG_annotations/kegg_query_all_transcripts/pathway-to-class.txt", header=F, sep = "\t")

names(path.class) <- c("pathway","class","description")
# something was funky, so I fixed it
path.class[path.class == "Folding"] <- "Folding sorting and degradation"
path.class <- path.class[- grep("sorting and degradation", path.class$pathway),]

# Merge the pathway information with the KO's
pathway.all <- merge(path.to.ko, path.name, by = "pathway", all = T)
pathway.all <- merge(pathway.all, path.class, by = "pathway", all = T)

# read in the KO's for the organism
trans.ko <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-199/trycycler/eggNOG_annotations/OXR-199_ko.txt", header = T, sep = "\t")

names(trans.ko)[names(trans.ko) == "value"] <- "ko"

# Merge the pathway information with the ko list
all <- merge(trans.ko, pathway.all, by = "ko", all = T)
all <- all[-c(4:12)]

# read in the annos with the DESeq info
deseq <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-199/trycycler/eggNOG_annotations/OXR-199_annos_w-DESeq.txt", header = T, sep = "\t")

deseq <- deseq[,c(1:8,33,34,46)]

# merge with all the pathway information
WOW <- merge(deseq, all, by = "eggNOG_name", all = T)
# remove NA's in the eggNOG_name field
WOW <- WOW[! is.na(WOW$eggNOG_name),]

output.file <- file("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-199/trycycler/eggNOG_annotations/OXR-199_all_data.txt", "wb")
write.table(WOW, file = output.file, row.names = F, col.names = T, sep = "\t")
close(output.file)

```

OXR-203
```{r}
library(dplyr)


# Read in the 
path.to.ko <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-203/trycycler/eggNOG_annotations/kegg_query_all_transcripts/Finaloutput.txt", header=F, sep = "")

names(path.to.ko) <- c("pathway","ko")

# read in pathway_name.txt
path.name <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-203/trycycler/eggNOG_annotations/kegg_query_all_transcripts/pathway_name.txt", header=F, sep = "\t")

names(path.name) <- c("pathway","name")

# read in pathway_name.txt
path.class <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-203/trycycler/eggNOG_annotations/kegg_query_all_transcripts/pathway-to-class.txt", header=F, sep = "\t")

names(path.class) <- c("pathway","class","description")
# something was funky, so I fixed it
path.class[path.class == "Folding"] <- "Folding sorting and degradation"
path.class <- path.class[- grep("sorting and degradation", path.class$pathway),]

# Merge the pathway information with the KO's
pathway.all <- merge(path.to.ko, path.name, by = "pathway", all = T)
pathway.all <- merge(pathway.all, path.class, by = "pathway", all = T)

# read in the KO's for the organism
trans.ko <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-203/trycycler/eggNOG_annotations/OXR-203_ko.txt", header = T, sep = "\t")

names(trans.ko)[names(trans.ko) == "value"] <- "ko"

# Merge the pathway information with the ko list
all <- merge(trans.ko, pathway.all, by = "ko", all = T)
all <- all[-c(4:12)]

# read in the annos with the DESeq info
deseq <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-203/trycycler/eggNOG_annotations/OXR-203_annos_w-DESeq.txt", header = T, sep = "\t")

deseq <- deseq[,c(1:8,33,34,46)]

# merge with all the pathway information
WOW <- merge(deseq, all, by = "eggNOG_name", all = T)
# remove NA's in the eggNOG_name field
WOW <- WOW[! is.na(WOW$eggNOG_name),]

output.file <- file("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-203/trycycler/eggNOG_annotations/OXR-203_all_data.txt", "wb")
write.table(WOW, file = output.file, row.names = F, col.names = T, sep = "\t")
close(output.file)

```

OXR-209
```{r}
library(dplyr)


# Read in the 
path.to.ko <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-209/trycycler/eggNOG_annotations/kegg_query_all_transcripts/Finaloutput.txt", header=F, sep = "")

names(path.to.ko) <- c("pathway","ko")

# read in pathway_name.txt
path.name <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-209/trycycler/eggNOG_annotations/kegg_query_all_transcripts/pathway_name.txt", header=F, sep = "\t")

names(path.name) <- c("pathway","name")

# read in pathway_name.txt
path.class <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-209/trycycler/eggNOG_annotations/kegg_query_all_transcripts/pathway-to-class.txt", header=F, sep = "\t")

names(path.class) <- c("pathway","class","description")
# something was funky, so I fixed it
path.class[path.class == "Folding"] <- "Folding sorting and degradation"
path.class <- path.class[- grep("sorting and degradation", path.class$pathway),]

# Merge the pathway information with the KO's
pathway.all <- merge(path.to.ko, path.name, by = "pathway", all = T)
pathway.all <- merge(pathway.all, path.class, by = "pathway", all = T)

# read in the KO's for the organism
trans.ko <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-209/trycycler/eggNOG_annotations/OXR-209_ko.txt", header = T, sep = "\t")

names(trans.ko)[names(trans.ko) == "value"] <- "ko"

# Merge the pathway information with the ko list
all <- merge(trans.ko, pathway.all, by = "ko", all = T)
all <- all[-c(4:12)]

# read in the annos with the DESeq info
deseq <- read.csv("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-209/trycycler/eggNOG_annotations/OXR-209_annos_w-DESeq.txt", header = T, sep = "\t")

deseq <- deseq[,c(1:8,33,34,46)]

# merge with all the pathway information
WOW <- merge(deseq, all, by = "eggNOG_name", all = T)
# remove NA's in the eggNOG_name field
WOW <- WOW[! is.na(WOW$eggNOG_name),]

output.file <- file("C:/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-209/trycycler/eggNOG_annotations/OXR-209_all_data.txt", "wb")
write.table(WOW, file = output.file, row.names = F, col.names = T, sep = "\t")
close(output.file)

```